server:
  port: 1119
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true     # 开启通过服务来访问config-server
        service-id: config-server    # 配置中心的服务名
      uri: http://localhost:1117/
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 开放 bus-refresh 接口，以便配合 bus 实现 配置的动态刷新
management:
  endpoints:          # 注意这里是endpoints，不是endpoint
    web:
      exposure:
        include: bus-refresh
  endpoint:
    bus-refresh:
      enabled: true   # 注意这里一定要设置为true