eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 1120
spring:
  application:
    name: zuul-service
zuul:
  routes:
    api-a:
      path: /client/**
      serviceId: eureka-client
    api-b:
      path: /ribbon/**
      serviceId: eureka-ribbon
